### ISSUE TITLE
Spike de RAM usage en Colab

### ISSUE THREAD

**Issue by sara-gf** [JavierBZ/Tarea3-IIC3697#29]
Holaa,

Para las primeras 150.000 iteraciones aprox el modelo de entrena perfectamente, el replay memory se va llenando y el use de RAM va aumentando bien de a poco. Pasado eso, el uso de RAM empieza a aumentar exponencialmente hasta que a las 166.000 colab crashea por exceso uso de RAM. No se si a alguien mas le ha pasado esto, porque online encontré a dos casos no mas y sin solución.

**Comment by xDanman** [comment]
A mi me paso que solo me soportaba una época con 250000, luego en la segunda se me reiniciaba y me decía que moría el colab. Al final solo compre colab pro y se me soluciono xD y eso que hasta ahora no he sobrepasado la ram y disco de la versión básica. Ramo pay to win.

**Comment by JavierBZ** [comment]
Sobre la memoria les puse en el enunciado que revisen bien como funcionan los LazyFrames de gym. 

Si entienden bien como funcionan no deberían tener problemas con usar una memoria de tamaño 500.000

**Comment by JavierBZ** [comment]
No es para nada necesario que usen Colab Pro, de hecho será mejor evaluada su implementación si es que no dependen de GPUs con más memoria.

**Comment by sara-gf** [comment]
Osea que es normal que para las primeras 150.000 iteraciones ocupe 3-4 gb pero que entre 150.000 y 166.000 salte a 13gb? Que ese es problema que tengo. Voy a revisar los LazyFrames a ver si algo de ahi esta causando problemas.

**Comment by JavierBZ** [comment]
No es normal, pero los lazy frames puede ser una de las razones. No te lo puedo asegurar 100%

**Comment by sara-gf** [comment]
Dale gracias, de ahi aviso si cacho que pasa, por si alguien le esta pasando tambien.

**Comment by xDanman** [comment]
Si es que hiciste la inicializacion de FrameStack y ProcessFrame84 como sale en la ayudantia, no deberias tener problemas con LazyFrames. Revisa como guardas los datos en la memoria con push, porque las obs tienen que quedar como objeto LazyFrame, no como np.array o tensor, o sino te come la memoria. Yo creo que deberia ser eso, si es que la memoria te aumenta sistemáticamente con el paso de la primera epoca.

**Comment by sara-gf** [comment]
En mis intentos de acelerar el sample cache que había cambiado el como guardaba una de las observaciones (estaba como array).  Arreglando todo corre perfect y usa nada de memoria. Ty ty <3
